### ISSUE TITLE
Ubuntu Performance counters for % Disk Used reporting precision

### ISSUE THREAD

**Issue by hestolz** [microsoft/SCXcore#145]
[Original issue was posted in OMS agent repo](https://github.com/microsoft/OMS-Agent-for-Linux/issues/782). SCX team please make time to respond. @vimish @rubroboletus

**Comment by JumpingYang001** [comment]
Fixed in [v1.6.9-2](https://github.com/microsoft/SCXcore/releases/tag/v1.6.9-2) https://github.com/microsoft/SCXcore/commit/59061ce0ba8613571dbc78be5a417393d68a1111.
