### ISSUE TITLE
SCX_UnixProcess returns no results on SunOS with Zones installed

### ISSUE THREAD

**Issue by rosenbom** [microsoft/SCXcore#159]
If you're monitoring Solaris System with Zones installed with SCX agent 1.6.2-343, querying SCX_UnixProcess class isn't returning results for services running in a zone other than 'global'. 
However, 'ps -ef' or 'ps -efZ' produce expected results. 
The only workaround to monitor Unix processes is to use ExecuteCommand methods and parse the output.

**Comment by JumpingYang001** [comment]
it was by design, didn't support that.
