### ISSUE TITLE
Checksum error for scx-1.6.4-7.universal.x64.rpm

### ISSUE THREAD

**Issue by kkbis** [microsoft/SCXcore#171]
Hi,

when trying to mirror the repository at https://packages.microsoft.com/centos/7/prod/ there is a checksum error for scx-1.6.4-7.universal.x64.rpm.

The repository metadata file says the checksum should be 

       7f4693c10b130ccfb40db6bcee88e98d5d67116b7984b1f5a81b721b86af4940

Downloading the file shows the actual checksum (SHA256) is 

       42b8943a8bbb45a810d6656d9887cf14c480e1d7a4e3ba20fc3d42518787665a.

Cheers,

kkbis

**Comment by JumpingYang001** [comment]
thanks for reporting it! we have published scx-1.6.8-0 under https://packages.microsoft.com/centos/7/prod/

**Comment by kkbis** [comment]
Thanks, works like a charm!
