### ISSUE TITLE
Give me a reason to exclude a particular file system.

### ISSUE THREAD

**Issue by kahota** [microsoft/SCXcore#178]
I would like to know why the SCX module of the Log Analytics agent does not collect logs for certain file systems, is it a functional limitation?
 
I have confirmed that the filesystems listed in the following documents are not collected by the SCX module.
https://github.com/microsoft/pal/blob/06c611367b1c31b3b6a6b65a9f58117fe54a9e95/source/code/scxsystemlib/disk/diskdepend.cpp#L719

My customer speculates that this may be due to the following. 
Is his understanding incorrect? If that is wrong, I would like to know the correct reason.
 
1. A symbolic area that does not actually use disk space, so it is not included in the list.
2. This area is created in the temporary area of the virtual machine in Azure, and is Not applicable because it will be deleted.

**Comment by JumpingYang001** [comment]
1, yes.
2. yes.
The FileSystemIgnored was in the first commit of the repro, I just close it. If you would like make it to be configurable, you should file DCR/RFC bug to Microsoft CSS team.
