### ISSUE TITLE
missing 1.6.9 release

### ISSUE THREAD

**Issue by Klaas-** [microsoft/SCXcore#179]
Hi,
it seems you have released a new version https://packages.microsoft.com/rhel/8/prod/scx-1.6.9-2.universal.x64.rpm but it's not reflected here.

Greetings
Klaas

**Comment by Klaas-** [comment]
Highlighting the people who did the last release @deepakjain111 @dishantcr7

**Comment by JumpingYang001** [comment]
updates:
https://github.com/microsoft/SCXcore/releases/tag/v1.6.9-2
