### ISSUE TITLE
SCXcore v1.8.1-0 .deb/.rpm release missing

### ISSUE THREAD

**Issue by gdarwish9** [microsoft/SCXcore#190]
Hi,

for version v1.8.1-0 there are no releases. Only source code.

Can you please provide them under _Assets_ like they are mentioned in the Package Checksum, see _scx-1.8.1-0.ssl_100.universal.x64.deb_

Thank you

**Comment by JumpingYang001** [comment]
@gdarwish9 checking.

**Comment by Yash-Khatri** [comment]
@gdarwish9 , The release is updated.
