### ISSUE TITLE
docs/SCX Provider Description.md hyperlinks point to scx.codeplex.com/wikipage

### ISSUE THREAD

**Issue by jasonzio** [Microsoft/SCXcore#81]
The API annotations (IN, OUT, etc.) in the SCX Provider Description.md doc are all hyperlinks that point to the wiki back at scx.codeplex.com.

**Comment by nirsingh** [comment]
Already resolved with https://github.com/Microsoft/SCXcore/commit/8a00c69fe00ccb7628fdf485b7776d2de3136326

**Comment by jasonzio** [comment]
Incorrect. Please search "SCX Provider Description.md" in that commit for the word "codeplex" and you'll see there are 25 hyperlinks that still point to that site. Those 25 hyperlinks are the ones that need to be changed.
