### ISSUE TITLE
SCX generates a certificate as part of scxsslconfig, and that certificate is owned by root:root, which cause omi with non-root feature can't start up

### ISSUE THREAD

**Issue by JumpingYang001** [Microsoft/SCXcore#83]
SCXcore’s scxsslconfig program should set the permissions to OMI due to the non-root changes. It was always weird that SCX was generating an OMI certificate, and now we were bitten by this. This can’t be done in postinstall, because scxsslconfig can be run after installation. So the program itself needs to set the permissions.

Repro steps:
1.	Run `sh scx-1.6.3-372.universal.x64.sh –install`
2.	Check /etc/opt/omi/ssl/omi.pem file permission, its permission is root:root. (As OMI designed architecture, its permission should be omi:omi.)
3.	Add https 5986 port in /etc/opt/omi/conf/omiserver.conf
4.	Restart omi: `/opt/omi/bin/service_control restart`
5.	Check omiengine process doesn’t start up.

Another way to repro the issue is to install omi*.rpm, then install scx*.rpm, it shows that scx package installing reverts /etc/opt/omi/ssl/omi.pem file permission from omi:omi to root:root.

**Comment by sarojcare** [comment]
Issue Fixed.
