### ISSUE TITLE
Program `scxsslconfig` now failing unit tests

### ISSUE THREAD

**Issue by jeffaco** [Microsoft/SCXcore#86]
Since commit hash `6fc4a5d`, unit tests are now failing:

```
---- All tests run ----


!!!FAILURES!!!
Test Results:
Run:  381   Failures: 1   Errors: 0


1) test: ScxSSLCertTest::testNonRFCcompliantDomainFallback (F) line: 494 /home/serviceb/jenkins/workspace/SCXCore-Runner/label/SUSE_10.0_X64/opsmgr/test/code/shared/tools/scx_ssl_config/scxsslcert_test.cpp
assertion failed
- Expression: ret == 0
- Error running: ./openssl_1.0.0/scxsslconfig, error message is: Error generating SSL certificate.  Use scxsslconfig to generate a new certificate, specifying host and domain names if necessary.  The error was: 'Unable to add the domain name to the subject.'
, error code is: 255


make: *** [testrun] Error 1
Build step 'Execute shell' marked build as failure
Finished: FAILURE
```

This is causing nightly build failures.

Normally, [pbuild](https://github.com/Microsoft/pbuild) should eliminate these sorts of failures. I'd like to understand how this occurred so that we can prevent failures like this in the future. Please collaborate with me on this so we can improve build reliability, thanks.

**Comment by sarojcare** [comment]
Issue fixed.

**Comment by macheretj** [comment]
Hi, experiencing similar issue on AIX system.

SCOM agent version: Version: 1.6.2-339

2018-01-29T07:10:44,964Z Warning    [scx.core.providers.runasprovider:682:22741088:1] SCX_OperatingSystem_Class_Provider::Invoke_ExecuteShellCommand - Failed to start thread: pthread_create failed, errno=11 -
[/home/serviceb/jenkins/workspace/SCXCore-Runner/label/aix_7.1/pal/source/code/scxcorelib/pal/scxthread.cpp:272]

Is that related? 
Directory /home/serviceb/jenkins/workspace/ does not exists.
